services:
  drupal:
    build:
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}_drupal"
    restart: always
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      APACHE_DOCUMENT_ROOT: /var/www/html/web # Drupal web root
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_POST_MAX_SIZE: 512M
      PHP_UPLOAD_MAX_FILESIZE: 512M
      PHP_MAX_EXECUTION_TIME: 240
      PHP_MEMORY_LIMIT: 512M
      PHP_DISPLAY_ERRORS: 1
      PHP_ERROR_REPORTING: E_ALL
      DRUSH_OPTIONS_URI: "http://${PROJECT_BASE_URL}:8080"
      COLUMNS: 80 # Set 80 columns for docker exec -it.
    volumes:
      - ./web/modules/custom:/var/www/html/web/modules/custom # custom modules
      - ./web/themes/custom:/var/www/html/web/themes/custom # custom themes
      - ./web/sites:/var/www/html/web/sites # sites directory
      - ./web/libraries:/var/www/html/web/libraries # libraries directory
      - ./web/profiles/custom:/var/www/html/web/profiles/custom # custom profiles
      - ./config:/var/www/html/config:consistent # site configuration
      - ./composer.json:/var/www/html/composer.json # composer file
      - ./composer.lock:/var/www/html/composer.lock # composer lock file
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - drupalnet

  mysql:
    image: mariadb:10.6
    container_name: "${PROJECT_NAME}_mysql"
    restart: always
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    # volumes:
    #   - mysql:/var/lib/mysql
    networks:
      - drupalnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: $DB_PORT
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    depends_on:
      - mysql
    networks:
      - drupalnet

volumes:
  dbdata:

networks:
  drupalnet:
