version: "3"
services:
  # MySQL Container
  mysql:
    image: mysql:5.6
    container_name: "${APP_NAME}-mysql"
    ports:
      - "${MYSQL_PORT}"
    command: --max_allowed_packet=128M
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    volumes:
      - my_drupal_data:/var/lib/mysql
   
  drupal:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: "${APP_NAME}-drupal"
    ports:
      - 8080
    command:
      - --port=8080
    logging:
      driver: "json-file"
    links:
      - "mysql:${APP_BASE_URL}_mysql"
    volumes:
      - ./:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/web
      DRUSH_OPTIONS_URI: "${APP_BASE_URL}"
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.http.services.drupal.loadbalancer.server.port=8080"
      - "traefik.enable=true"
      - "traefik.http.routers.drupal.rule=Host(`${APP_BASE_URL}`)"
      - "traefik.http.routers.drupal.entrypoints=web"
      - "traefik.port=80"
      - "traefik.default.protocol=http"
    depends_on:
      - mysql
 
  # Traefik Contaniner
  traefik:
    image: traefik:v2.0
    container_name: "${APP_NAME}-traefik"
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      # Dashboard
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
    depends_on:
      - drupal

volumes:
  my_drupal_data: